// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

interface Infeglobal {
    function getUserLevel(uint256 nodeId) external view returns (uint256);
    function nodeId(address wallet) external view returns (uint256);
    function getNodeWallet(uint256 nodeId) external view returns (address);
    function unlockTier(uint256 _nodeId, uint256 _toTier) external payable;
}

/**
 * @title IncomeVaultHelper
 * @notice Stores and vests rewards generated by NFEGlobal and RewardPool.
 *         Genesis Node (55555) is completely exempt and receives direct payments.
 *         Linear daily vesting schedule ReleaseDays = Tier * 5.
 */
contract IncomeVaultHelper is ReentrancyGuard, Ownable {

    struct VestingDeposit {
        uint256 amount;
        uint256 released;
        uint256 startTime;
        uint256 releaseDays;
    }

    struct UserStats {
        uint256 totalDeposited;
        uint256 totalClaimed;
        uint256 totalReinvested;
        uint256 totalInstantWithdrawn;
        uint256 totalPenaltiesPaid;
    }

    // Contracts & addresses
    address public core;
    address public rewardPool;
    address public feeReceiver;

    uint256 public constant GENESIS_NODE_ID = 55555;

    // Basis points limits
    uint256 public instantWithdrawFeeBP = 2000; // 20%
    uint256 public rewardPoolShareBP = 8000;    // 80% of penalty
    uint256 public feeReceiverShareBP = 2000;   // 20% of penalty

    bool public paused;

    mapping(uint256 => VestingDeposit[]) public userDeposits;
    mapping(uint256 => UserStats) public userStats;

    // Events
    event Deposited(uint256 indexed nodeId, uint256 amount, uint256 releaseDays);
    event Claimed(uint256 indexed nodeId, address indexed wallet, uint256 amount);
    event Reinvested(uint256 indexed nodeId, uint256 targetTier, uint256 amount);
    event InstantWithdrawn(uint256 indexed nodeId, address indexed wallet, uint256 amount, uint256 netPayout, uint256 penalty);
    event PausedStateUpdated(bool status);
    event PenaltyParamsUpdated(uint256 instantWithdrawFeeBP, uint256 rewardPoolShareBP, uint256 feeReceiverShareBP);
    event CoreUpdated(address oldCore, address newCore);
    event RewardPoolUpdated(address oldPool, address newPool);
    event FeeReceiverUpdated(address oldReceiver, address newReceiver);

    modifier whenNotPaused() {
        require(!paused, "Vault is paused");
        _;
    }

    constructor(
        address _core,
        address _rewardPool,
        address _feeReceiver
    ) {
        require(_core != address(0), "Zero core address");
        require(_rewardPool != address(0), "Zero pool address");
        require(_feeReceiver != address(0), "Zero fee receiver address");
        core = _core;
        rewardPool = _rewardPool;
        feeReceiver = _feeReceiver;
    }

    receive() external payable {}

    /**
     * @notice Deposit BNB to vest for a node.
     *         Callable only by NFEGlobal Core or RewardPool.
     */
    function deposit(uint256 nodeId) external payable nonReentrant whenNotPaused {
        require(msg.sender == core || msg.sender == rewardPool, "Unauthorized source");
        require(nodeId != GENESIS_NODE_ID, "Genesis exempt");
        require(msg.value > 0, "Zero amount");

        uint256 tier = Infeglobal(core).getUserLevel(nodeId);
        if (tier == 0) {
            tier = 1; // Safeguard fallback if tier is 0
        }
        uint256 releaseDays = tier * 5;

        userDeposits[nodeId].push(VestingDeposit({
            amount: msg.value,
            released: 0,
            startTime: block.timestamp,
            releaseDays: releaseDays
        }));

        userStats[nodeId].totalDeposited += msg.value;

        emit Deposited(nodeId, msg.value, releaseDays);
    }

    /**
     * @notice Claim all vested rewards for msg.sender's node.
     */
    function claim() external nonReentrant whenNotPaused {
        uint256 nodeId = Infeglobal(core).nodeId(msg.sender);
        require(nodeId != 0, "Not a registered node");
        require(nodeId != GENESIS_NODE_ID, "Genesis exempt");

        uint256 totalVestedClaimable = 0;
        uint256 len = userDeposits[nodeId].length;

        for (uint256 i = 0; i < len; i++) {
            VestingDeposit storage dep = userDeposits[nodeId][i];
            uint256 claimable = _calculateClaimable(dep);
            if (claimable > 0) {
                dep.released += claimable;
                totalVestedClaimable += claimable;
            }
        }

        require(totalVestedClaimable > 0, "Nothing claimable");
        userStats[nodeId].totalClaimed += totalVestedClaimable;

        (bool success, ) = payable(msg.sender).call{value: totalVestedClaimable}("");
        require(success, "Transfer failed");

        emit Claimed(nodeId, msg.sender, totalVestedClaimable);
    }

    /**
     * @notice Reinvest vested rewards to upgrade a user's node tier.
     *         No penalty or withdrawal fee applies.
     */
    function reinvest(uint256 targetTier, uint256 amount) external nonReentrant whenNotPaused {
        uint256 nodeId = Infeglobal(core).nodeId(msg.sender);
        require(nodeId != 0, "Not a registered node");
        require(nodeId != GENESIS_NODE_ID, "Genesis exempt");
        require(amount > 0, "Zero amount");

        // Verify user has enough vested balance
        uint256 totalVestedAvailable = 0;
        uint256 len = userDeposits[nodeId].length;

        for (uint256 i = 0; i < len; i++) {
            VestingDeposit storage dep = userDeposits[nodeId][i];
            totalVestedAvailable += _calculateClaimable(dep);
        }
        require(totalVestedAvailable >= amount, "Insufficient vested balance");

        // Deduct from deposits starting from oldest (FIFO)
        uint256 remainingToDeduct = amount;
        for (uint256 i = 0; i < len && remainingToDeduct > 0; i++) {
            VestingDeposit storage dep = userDeposits[nodeId][i];
            uint256 claimable = _calculateClaimable(dep);
            if (claimable > 0) {
                if (claimable >= remainingToDeduct) {
                    dep.released += remainingToDeduct;
                    remainingToDeduct = 0;
                } else {
                    dep.released += claimable;
                    remainingToDeduct -= claimable;
                }
            }
        }

        userStats[nodeId].totalReinvested += amount;

        // Perform the upgrade
        uint256 balBefore = address(this).balance;
        Infeglobal(core).unlockTier{value: amount}(nodeId, targetTier);
        uint256 balAfter = address(this).balance;

        // Handle possible refunds of excess BNB
        uint256 expectedBal = balBefore - amount;
        if (balAfter > expectedBal) {
            uint256 refund = balAfter - expectedBal;
            userDeposits[nodeId].push(VestingDeposit({
                amount: refund,
                released: 0,
                startTime: block.timestamp,
                releaseDays: 0 // Refund of own money is immediately claimable
            }));
            userStats[nodeId].totalReinvested -= refund;
        }

        emit Reinvested(nodeId, targetTier, amount);
    }

    /**
     * @notice Withdraw locked or vested funds immediately with a flat 20% penalty.
     */
    function instantWithdraw(uint256 amount) external nonReentrant whenNotPaused {
        uint256 nodeId = Infeglobal(core).nodeId(msg.sender);
        require(nodeId != 0, "Not a registered node");
        require(nodeId != GENESIS_NODE_ID, "Genesis exempt");
        require(amount > 0, "Zero amount");

        // Verify user has enough total balance (locked + claimable)
        uint256 totalAvailable = 0;
        uint256 len = userDeposits[nodeId].length;

        for (uint256 i = 0; i < len; i++) {
            VestingDeposit memory dep = userDeposits[nodeId][i];
            totalAvailable += (dep.amount - dep.released);
        }
        require(totalAvailable >= amount, "Insufficient vault balance");

        // Deduct from deposits starting from oldest
        uint256 remainingToDeduct = amount;
        for (uint256 i = 0; i < len && remainingToDeduct > 0; i++) {
            VestingDeposit storage dep = userDeposits[nodeId][i];
            uint256 unreleased = dep.amount - dep.released;
            if (unreleased > 0) {
                if (unreleased >= remainingToDeduct) {
                    dep.released += remainingToDeduct;
                    remainingToDeduct = 0;
                } else {
                    dep.released = dep.amount;
                    remainingToDeduct -= unreleased;
                }
            }
        }

        // Apply penalty fee
        uint256 penalty = (amount * instantWithdrawFeeBP) / 10000;
        uint256 netPayout = amount - penalty;

        userStats[nodeId].totalInstantWithdrawn += netPayout;
        userStats[nodeId].totalPenaltiesPaid += penalty;

        // Distribute penalty
        if (penalty > 0) {
            uint256 poolAmt = (penalty * rewardPoolShareBP) / 10000;
            uint256 feeAmt = penalty - poolAmt;

            if (poolAmt > 0 && rewardPool != address(0)) {
                (bool pSuccess, ) = payable(rewardPool).call{value: poolAmt}("");
                if (!pSuccess) {
                    // Fallback to feeReceiver if RewardPool transfer fails
                    feeAmt += poolAmt;
                    poolAmt = 0;
                }
            }
            if (feeAmt > 0 && feeReceiver != address(0)) {
                (bool fSuccess, ) = payable(feeReceiver).call{value: feeAmt}("");
                require(fSuccess, "Fee distribution failed");
            }
        }

        // Pay net amount to user
        (bool success, ) = payable(msg.sender).call{value: netPayout}("");
        require(success, "Payout transfer failed");

        emit InstantWithdrawn(nodeId, msg.sender, amount, netPayout, penalty);
    }

    // =========================================================================
    // View functions
    // =========================================================================

    function getClaimable(uint256 nodeId) public view returns (uint256 totalClaimable) {
        uint256 len = userDeposits[nodeId].length;
        for (uint256 i = 0; i < len; i++) {
            totalClaimable += _calculateClaimable(userDeposits[nodeId][i]);
        }
    }

    function getLockedBalance(uint256 nodeId) public view returns (uint256 totalLocked) {
        uint256 len = userDeposits[nodeId].length;
        for (uint256 i = 0; i < len; i++) {
            VestingDeposit memory dep = userDeposits[nodeId][i];
            uint256 unreleased = dep.amount - dep.released;
            uint256 claimable = _calculateClaimable(dep);
            totalLocked += (unreleased - claimable);
        }
    }

    function getTotalVaultBalance(uint256 nodeId) public view returns (uint256 totalBalance) {
        uint256 len = userDeposits[nodeId].length;
        for (uint256 i = 0; i < len; i++) {
            VestingDeposit memory dep = userDeposits[nodeId][i];
            totalBalance += (dep.amount - dep.released);
        }
    }

    function getDepositCount(uint256 nodeId) external view returns (uint256) {
        return userDeposits[nodeId].length;
    }

    function getDepositInfo(uint256 nodeId, uint256 index) external view returns (
        uint256 amount,
        uint256 released,
        uint256 startTime,
        uint256 releaseDays
    ) {
        require(index < userDeposits[nodeId].length, "Index out of bounds");
        VestingDeposit memory dep = userDeposits[nodeId][index];
        return (dep.amount, dep.released, dep.startTime, dep.releaseDays);
    }

    function getVestingSchedule(uint256 nodeId, uint256 index) external view returns (
        uint256 startTime,
        uint256 releaseDays,
        uint256 duration,
        uint256 timeRemaining,
        uint256 vestedAmount,
        uint256 lockedAmount
    ) {
        require(index < userDeposits[nodeId].length, "Index out of bounds");
        VestingDeposit memory dep = userDeposits[nodeId][index];
        startTime = dep.startTime;
        releaseDays = dep.releaseDays;
        duration = dep.releaseDays * 1 days;

        uint256 elapsed = block.timestamp > startTime ? block.timestamp - startTime : 0;
        timeRemaining = elapsed >= duration ? 0 : duration - elapsed;

        uint256 totalVested = 0;
        if (elapsed >= duration) {
            totalVested = dep.amount;
        } else {
            totalVested = (dep.amount * elapsed) / duration;
        }

        vestedAmount = totalVested;
        lockedAmount = dep.amount > totalVested ? dep.amount - totalVested : 0;
    }

    function getUserVaultStats(uint256 nodeId) external view returns (
        uint256 totalDeposited,
        uint256 totalClaimed,
        uint256 totalReinvested,
        uint256 totalInstantWithdrawn,
        uint256 totalPenaltiesPaid
    ) {
        UserStats memory stats = userStats[nodeId];
        return (
            stats.totalDeposited,
            stats.totalClaimed,
            stats.totalReinvested,
            stats.totalInstantWithdrawn,
            stats.totalPenaltiesPaid
        );
    }

    // =========================================================================
    // Admin functions
    // =========================================================================

    function setCore(address _core) external onlyOwner {
        require(_core != address(0), "Zero core address");
        address old = core;
        core = _core;
        emit CoreUpdated(old, _core);
    }

    function setRewardPool(address _rewardPool) external onlyOwner {
        require(_rewardPool != address(0), "Zero pool address");
        address old = rewardPool;
        rewardPool = _rewardPool;
        emit RewardPoolUpdated(old, _rewardPool);
    }

    function setFeeReceiver(address _feeReceiver) external onlyOwner {
        require(_feeReceiver != address(0), "Zero fee receiver address");
        address old = feeReceiver;
        feeReceiver = _feeReceiver;
        emit FeeReceiverUpdated(old, _feeReceiver);
    }

    function setInstantWithdrawFee(uint256 _feeBP) external onlyOwner {
        require(_feeBP <= 5000, "Fee too high (max 50%)");
        instantWithdrawFeeBP = _feeBP;
        emit PenaltyParamsUpdated(instantWithdrawFeeBP, rewardPoolShareBP, feeReceiverShareBP);
    }

    function setPenaltySplit(uint256 _rpBP, uint256 _feeBP) external onlyOwner {
        require(_rpBP + _feeBP == 10000, "Split must sum to 10000");
        rewardPoolShareBP = _rpBP;
        feeReceiverShareBP = _feeBP;
        emit PenaltyParamsUpdated(instantWithdrawFeeBP, rewardPoolShareBP, feeReceiverShareBP);
    }

    function pauseVault() external onlyOwner {
        paused = true;
        emit PausedStateUpdated(true);
    }

    function unpauseVault() external onlyOwner {
        paused = false;
        emit PausedStateUpdated(false);
    }

    function emergencyRecover(address token, uint256 amount) external onlyOwner {
        if (token == address(0)) {
            (bool success, ) = payable(owner()).call{value: amount}("");
            require(success, "BNB recovery failed");
        } else {
            (bool success, bytes memory data) = token.call(
                abi.encodeWithSignature("transfer(address,uint256)", owner(), amount)
            );
            require(success && (data.length == 0 || abi.decode(data, (bool))), "Token recovery failed");
        }
    }

    // =========================================================================
    // Internal helper
    // =========================================================================

    function _calculateClaimable(VestingDeposit memory dep) internal view returns (uint256) {
        if (dep.released >= dep.amount) {
            return 0;
        }
        uint256 duration = dep.releaseDays * 1 days;
        if (block.timestamp < dep.startTime) {
            return 0;
        }
        uint256 elapsed = block.timestamp - dep.startTime;
        uint256 totalVested = 0;
        if (elapsed >= duration) {
            totalVested = dep.amount;
        } else {
            totalVested = (dep.amount * elapsed) / duration;
        }

        if (totalVested <= dep.released) {
            return 0;
        }
        return totalVested - dep.released;
    }
}
